### PR TITLE
Add support for = in parameter values.

### PR DESCRIPTION
**Pull request by ttyniwa**
This PR resolve https://github.com/jwmach1/parameterized-scheduler/issues/10

### CODE REVIEW

**Comment by shinusuresh** [comment]
👍 for the PR

**Comment by vanclist** [comment]
Is there anything that holds this PR to be merged?

**Comment by ttyniwa** [comment]
@batmat Could you merge this one?

**Comment by dhingraaditya** [comment]
Can someone please merge this ? Please and thanks !

**Comment by rajeshvaralli** [comment]
anybody looking into this merge? What's stopping from merging this PR?

**Comment by RogersSauravGoyal** [comment]
@batmat Could you merge this one. Please tell us If  there is any issue.

**Comment by boredomwontgetus** [comment]
Any news on this PR? Is there a reason this not merged yet?

**Review by res0nance — APPROVED** [review]

**Pull request merged**
