### PR TITLE
JENKINS-37139 JENKINS-44031 add support for declarative pipelines as parameterizedCron trigger + updated checkSanity function to operate on multi-line strings, fixes "'%' characters are present" error

### PR DESCRIPTION
**Pull request by colourmeamused**
A small fix to support declarative pipelines. Would be nice to get this in a 0.4.1 release. This plugin provides a badly needed feature!

### CODE REVIEW

**Comment by kayrus** [comment]
Now I know why this plugin doesn't trigger declarative pipelines.

**Comment by colourmeamused** [comment]
Merged in latest changes from jwmach1/parameterized-scheduler. Snapshop build below for anyone who wants to try it out.

[parameterized-scheduler.zip](https://github.com/jenkinsci/parameterized-scheduler-plugin/files/1118021/parameterized-scheduler.zip)

**Comment by colourmeamused** [comment]
@jwmach1 I didn't see a pull request so I merged in your changes to fix JENKINS-44031. Do you have commit access to this repo?

**Comment by jwmach1** [comment]
I do not. However, I'd walked away from the project after the end-of-life of the project I was using it on.  I'm just facilitating so the upstream changes can make it here - where you-all have the plugin registered with Jenkins.

**Pull request merged**
